# Generated by Django 2.2 on 2021-03-13 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='excel_file',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('xls', 'xlsx'), message='Допускаются только файлы Excel')], verbose_name='Сам файл'),
        ),
    ]
